Repository kennethnym/StarlightLauncher, pull requests merged in 2022-08, with the labels that each got.

#20 Add a refresh button next to current weather
  app/src/main/java/kenneth/app/starlightlauncher/views/DateTimeView.kt
  app/src/main/res/drawable/ic_redo.xml
  app/src/main/res/layout/date_time_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#22 Allow back button to clear search box content
  app/src/main/java/kenneth/app/starlightlauncher/views/SearchBox.kt
  app/src/main/java/kenneth/app/starlightlauncher/widgets/widgetspanel/WidgetsPanel.kt
Labels: enhancement

#28 Update license
  LICENSE
  README.md
Labels: documentation

#32 All notes overlay layout improvements
  .idea/misc.xml
  app/src/main/java/kenneth/app/starlightlauncher/widgets/widgetspanel/Overlay.kt
  notes-widget/src/main/java/kenneth/app/starlightlauncher/noteswidget/view/AllNotes.kt
Labels: bug

#34 initial fastlane structures
  fastlane/metadata/android/de/short_description.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/01.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/02.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/03.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/04.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/05.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/06.jpg
  fastlane/metadata/android/en-US/short_description.txt
Labels: enhancement
